name: cx

on: push

env:
  AWS_REGION: us-east-1
  API_STAGE_NAME: "v0"
  ACCESS_LOG_RETENTION_DAYS: 7
  FUNC_MEMORY_SIZE: 128
  FUNC_TIMEOUT: 5
  FUNC_LOG_RETENTION_DAYS: 7
  PROFILE_TABLE_READ_SCALING_MIN_CAPACITY: 1
  PROFILE_TABLE_WRITE_SCALING_MIN_CAPACITY: 1

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CFN_TEMPLATES: "stack.yml\n.github/cd_setup.yml\n"
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate all cloudformation templates
        run: |
          printf "${{ env.CFN_TEMPLATES }}" | while read template; do
            aws cloudformation validate-template \
              --template-body="file://$template"
          done
