name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CFN_TEMPLATES: "stack.yml\n.github/cd_setup.yml\n"
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
